ALTER TABLE DS_MORIVER
ADD SUBSAMPLE_TYPE VARCHAR2(1);

-- ----------------------------------------------------------

CREATE TABLE SUBSAMPLE_TYPE_LK (
    ST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE VARCHAR2(1 BYTE),
    DESCRIPTION VARCHAR2(20 BYTE),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO SUBSAMPLE_TYPE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('S', 'Standard', 'T');

INSERT INTO SUBSAMPLE_TYPE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('T', 'Targeted', 'T');

-- ----------------------------------------------------------

CREATE TABLE U6_LK (
    U6_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE VARCHAR2(5 BYTE),
    DESCRIPTION VARCHAR2(20 BYTE),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO U6_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('MNCF', 'MNCF', 'T');

INSERT INTO U6_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('NSTS', 'NSTS', 'F');

-- ----------------------------------------------------------

CREATE TABLE MICRO_STRUCTURE_LK (
    MS_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE NUMBER,
    DESCRIPTION VARCHAR2(20),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (0, 'NOT DESCRIBED', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'L DIKE', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'WING DIKE', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'KICKER DIKE', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'ROOTLESS', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'CHEVRON', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (6, 'CHANNEL SAND BAR', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'BANK LINE', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (8, 'CHUTE', 'T');

INSERT INTO MICRO_STRUCTURE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (9, 'HIGHLY ENGINEERED', 'T');

-- ----------------------------------------------------------

CREATE TABLE STRUCTURE_FLOW_LK (
    SF_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE NUMBER,
    DESCRIPTION VARCHAR2(20),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO STRUCTURE_FLOW_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (0, 'CODE', 'F');

INSERT INTO STRUCTURE_FLOW_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (0, 'NOT DESCRIBED', 'T');

INSERT INTO STRUCTURE_FLOW_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'DRY', 'T');

INSERT INTO STRUCTURE_FLOW_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'PARTIAL', 'T');

INSERT INTO STRUCTURE_FLOW_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'OVERFLOWING', 'T');

INSERT INTO STRUCTURE_FLOW_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'HIGH WATER', 'T');

INSERT INTO STRUCTURE_FLOW_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'NO FLOW', 'T');

-- ----------------------------------------------------------

CREATE TABLE STRUCTURE_MOD_LK (
    SM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE NUMBER,
    DESCRIPTION VARCHAR2(30),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (0, 'NOT DESCRIBED', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'NATURAL', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'SINGLE LG', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'UNNOTCHED', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'ANGLED OR PARALLEL', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'BANK NOTCH', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'PILOT < 5 YEARS', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'REVETED', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'SINGLE SM', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'BEDROCK', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'BRAIDED', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'PILOT > 5 YEARS', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'TOP NOTCH', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'ISLAND SERIES', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'RR EMBANKMENT', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'SIDE NOTCH', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'BACK WATER', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'NATURAL STEEP', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'TOP & SIDE NOTCH', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (6, 'BANK & TOP & SIDE NOTCH', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'BANK & TOP NOTCH', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (8, 'BANK & SIDE NOTCH', 'T');

INSERT INTO STRUCTURE_MOD_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (9, 'NOTCH (UNDEFINED)', 'T');

-- ----------------------------------------------------------

CREATE TABLE SET_SITE_1_LK (
    SS1_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE NUMBER,
    DESCRIPTION VARCHAR2(20),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (0, 'NOT DESCRIBED', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'POOL', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'BAR', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'OPEN WATER', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'BANK', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (6, 'SCALLOP', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'COMBINED', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (8, 'TIE CHANNEL', 'T');

INSERT INTO SET_SITE_1_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (9, 'SIDE CHNL SMALL', 'T');

-- ----------------------------------------------------------

CREATE TABLE SET_SITE_2_LK (
    SS2_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE NUMBER,
    DESCRIPTION VARCHAR2(30),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (0, 'NOT DESCRIBED', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'BANK', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'BANK NOTCH', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'HEAD', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'INFLOW HEAD', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'INSIDE EDDY', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'POOL AND BAR', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (1, 'REVETMENT', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'BANK SIDE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'BODY', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'INFLOW BODY', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'NOTCH', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'OUT SIDE EDDY', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'POOL AND OPEN WATER', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'RED ROCK', 'F');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'REDROCK', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'TOP', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (2, 'TOP NOTCH', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'BAR AND OPEN WATER', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'CHANNEL SIDE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'CONFLUENCE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'EDDY LINE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'INFLOW CONFLUENCE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'PILINGS', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'SIDE  NOTCH', 'F');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (3, 'SIDE NOTCH', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'DIKE TIP AND OPEN WATER', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'LIP', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'NATURAL', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'OUTFLOW HEAD', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'TAIL', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (4, 'TIP', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'FLAT', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'HEAD', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'NATURAL STEEP', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'NO NOTCH', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (5, 'OUTFLOW BODY', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (6, 'BANK AND OPEN WATER', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (6, 'CROWN', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (6, 'NOTCH (UNDEFINED)', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (6, 'OUTFLOW CONFLUENCE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'BACKWATER', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'BANK AND SCALLOP', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'CHANNEL SIDE TIP', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'DIKE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (7, 'PLUNGE', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (8, 'BANK SIDE TIP', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (8, 'BRAIDED', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (8, 'SNAG', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (9, 'ISLAND', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (9, 'NOTCH SCOUR', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (9, 'SHOAL', 'T');

INSERT INTO SET_SITE_2_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES (9, 'UNDEFINED', 'T');