ALTER TABLE DS_FISH
ADD LENGTH_TYPE VARCHAR2(2);

ALTER TABLE DS_FISH
ADD TAGNUMBER NUMBER(14, 4);

ALTER TABLE DS_FISH
ADD COMMON_NAME VARCHAR2(255 BYTE);

-- ----------------------------

CREATE TABLE LENGTH_TYPE_LK (
    LT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE VARCHAR2(2 BYTE),
    DESCRIPTION VARCHAR2(20 BYTE),
    ACTIVE_FLAG_TF VARCHAR2(1 BYTE)
);

INSERT INTO LENGTH_TYPE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('FF', 'Fork Length - Field', 'T');

INSERT INTO LENGTH_TYPE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('TF', 'Total Length - Field', 'T');

INSERT INTO LENGTH_TYPE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('FL', 'Fork Length - Lab', 'T');

INSERT INTO LENGTH_TYPE_LK (CODE, DESCRIPTION, ACTIVE_FLAG_TF)
VALUES ('TL', 'Total Length - Lab', 'T');

