-- Apply to TEST environment only -- 
-- DB Script applied 7/24/2026 --

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (19, 14, 1, null, 10, 0, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (20, 14, 2, null, 20, 10.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (21, 14, 3, null, 30, 20.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (22, 14, 4, null, 40, 30.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (23, 14, 5, null, 50, 40.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (24, 14, 6, null, 60, 50.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (25, 14, 7, null, 70, 60.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (26, 14, 8, null, 80, 70.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (27, 14, 9, null, 90, 80.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (28, 14, 10, null, 100, 90.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (29, 14, 11, null, 110, 100.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (30, 14, 12, null, 120.1, 110.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (31, 14, 13, null, 130.2, 120.2, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (32, 13, 1, null, 140.3, 130.3, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (33, 13, 2, null, 150.3, 140.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (34, 13, 3, null, 160.3, 150.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (35, 13, 4, null, 170.3, 160.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (36, 13, 5, null, 180.3, 170.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (37, 13, 6, null, 190.3, 180.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (38, 13, 7, null, 200.3, 190.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (39, 13, 8, null, 210.3, 200.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (40, 13, 9, null, 220.3, 210.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (41, 13, 10, null, 230.3, 220.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (42, 13, 11, null, 240.3, 230.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (43, 13, 12, null, 250.3, 240.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (44, 10, 1, null, 260.2, 250.4, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (45, 10, 2, null, 270.1, 260.3, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (46, 10, 3, null, 280, 270.2, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (47, 10, 4, null, 289.9, 280.1, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (48, 10, 5, null, 299.8, 290, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (49, 10, 6, null, 309.7, 299.9, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (50, 10, 7, null, 319.6, 309.8, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (51, 10, 8, null, 329.5, 319.7, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (52, 10, 9, null, 339.4, 329.6, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (53, 10, 10, null, 349.2, 339.5, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (54, 10, 11, null, 359, 349.3, 'A0', 1);

INSERT INTO REACH_LK (REACH_ID, SEGMENT_ID, REACH_CODE, REACH_DESC, UPPER_RIVER_MILE, LOWER_RIVER_MILE, SEASON, PROJECT_ID)
VALUES (55, 10, 12, null, 368.9, 359.1, 'A0', 1);