REM ### Create UPLOAD_PROCEDURE Table ###
SET DEFINE OFF;
CREATE TABLE UPLOAD_PROCEDURE (
ID			NUMBER
,P_FID			VARCHAR2(50 BYTE)
,S_FID			VARCHAR2(50 BYTE)
,S_ID			NUMBER
,PURPOSE_CODE		VARCHAR2(2 BYTE)
,PROCEDURE_DATE		DATE
,PROCEDURE_START_TIME	VARCHAR2(11 BYTE)
,PROCEDURE_END_TIME	VARCHAR2(11 BYTE)
,PROCEDURE_BY		VARCHAR2(3 BYTE)
,ANTIBIOTIC_INJECTION_IND	NUMBER
,PHOTO_DORSAL_IND	NUMBER
,PHOTO_VENTRAL_IND	NUMBER
,PHOTO_LEFT_IND		NUMBER
,OLD_RADIO_TAG_NUM	NUMBER
,OLD_FREQUENCY_ID	NUMBER
,DST_SERIAL_NUM		NUMBER
,DST_START_DATE		DATE
,DST_START_TIME		VARCHAR2(11 BYTE)
,DST_REIMPLANT_IND	NUMBER
,NEW_RADIO_TAG_NUM	NUMBER
,NEW_FREQUENCY_ID	NUMBER
,SEX_CODE		VARCHAR2(1 BYTE)
,COMMENTS		VARCHAR2(2000 BYTE)
,FISH_HEALTH_COMMENTS	VARCHAR2(2000 BYTE)
,SPAWN_CODE		VARCHAR2(2 BYTE)
,EVAL_LOCATION_CODE	VARCHAR2(2 BYTE)
,BLOOD_SAMPLE_IND	NUMBER
,EGG_SAMPLE_IND		NUMBER
,VISUAL_REPRO_STATUS_CODE	VARCHAR2(4 BYTE)
,ULTRASOUND_REPRO_STATUS_CODE	VARCHAR2(4 BYTE)
,ULTRASOUND_GONAD_LENGTH	NUMBER
,GONAD_CONDITION		VARCHAR2(50 BYTE)
,EXPECTED_SPAWN_YEAR	NUMBER
,LAST_UPDATED		DATE
,UPLOAD_SESSION_ID	NUMBER
,UPLOADED_BY		VARCHAR2(20 BYTE)
,UPLOAD_FILENAME	VARCHAR2(200 BYTE)
,CONSTRAINT UPLOAD_PROCEDURE_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN UPLOAD_PROCEDURE.ID IS 'Primary Key. ID';
COMMENT ON COLUMN UPLOAD_PROCEDURE.P_FID IS 'Field app procedure ID';
COMMENT ON COLUMN UPLOAD_PROCEDURE.UPLOAD_SESSION_ID IS 'Upload Session ID. FK to UPLOAD_SESSION.ID';
COMMENT ON COLUMN UPLOAD_PROCEDURE.S_FID IS 'Supplemental ID parent to procedure. FK to UPLOAD_SUPPLEMENTAL.S_FID';
COMMENT ON COLUMN UPLOAD_PROCEDURE.S_ID IS 'Supplemental ID parent to procedure. FK to UPLOAD_SUPPLEMENTAL.S_ID';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PURPOSE_CODE IS 'Purpose Code. FK to PURPOSE_LK.CODE';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PROCEDURE_DATE IS 'Date of the procedure';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PHOTO_DORSAL_IND IS 'If have photo of the dorsal side of head. 1  photo taken, 0 no photo';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PHOTO_VENTRAL_IND IS 'If have Photo of the ventral side of head. 1  photo taken, 0 no photo';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PHOTO_VENTRAL_IND IS 'If have Photo of the left side of head. 1  photo taken, 0 no photo';
COMMENT ON COLUMN UPLOAD_PROCEDURE.OLD_RADIO_TAG_NUM IS 'Previous radio tag number';
COMMENT ON COLUMN UPLOAD_PROCEDURE.OLD_FREQUENCY_ID IS 'Previous radio tag frequency. FK to FREQUENCY_LK.ID';
COMMENT ON COLUMN UPLOAD_PROCEDURE.DST_SERIAL_NUM IS 'DST Serial Number';
COMMENT ON COLUMN UPLOAD_PROCEDURE.DST_START_DATE IS 'DST Start Date';
COMMENT ON COLUMN UPLOAD_PROCEDURE.DST_START_TIME IS 'DST Start Time';
COMMENT ON COLUMN UPLOAD_PROCEDURE.DST_REIMPLANT_IND IS 'Reimplant tag. 1 was reimplanted, 0 not a reimplant';
COMMENT ON COLUMN UPLOAD_PROCEDURE.NEW_RADIO_TAG_NUM IS 'New radio tag number';
COMMENT ON COLUMN UPLOAD_PROCEDURE.NEW_FREQUENCY_ID IS 'New radio tag frequency. FK to FREQUENCY_LK.ID';
COMMENT ON COLUMN UPLOAD_PROCEDURE.SEX_CODE IS 'Sex code for the fish. FK to SEX_LK.CODE';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PROCEDURE_BY IS 'Initials of the person performing the procedure';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PROCEDURE_START_TIME IS 'Start time of the procedure';
COMMENT ON COLUMN UPLOAD_PROCEDURE.PROCEDURE_END_TIME IS 'End time of the procedure';
COMMENT ON COLUMN UPLOAD_PROCEDURE.ANTIBIOTIC_INJECTION_IND IS 'If an antibiotic injection was given. 1 - yes, 0 - no';
COMMENT ON COLUMN UPLOAD_PROCEDURE.COMMENTS IS 'Comments on the procedure';
COMMENT ON COLUMN UPLOAD_PROCEDURE.FISH_HEALTH_COMMENTS IS 'Comments on fish health';
COMMENT ON COLUMN UPLOAD_PROCEDURE.SPAWN_CODE IS 'Spawn status code. FK to SPAWN_LK.CODE';
COMMENT ON COLUMN UPLOAD_PROCEDURE.EVAL_LOCATION_CODE IS 'Evaluation location code. FK to EVAL_LOCATION_LK.CODE';
COMMENT ON COLUMN UPLOAD_PROCEDURE.BLOOD_SAMPLE_IND IS 'If blood sample was taken. 1 - yes, 0 - no';
COMMENT ON COLUMN UPLOAD_PROCEDURE.EGG_SAMPLE_IND IS 'If egg sample was taken. 1 - yes, 0 - no';
COMMENT ON COLUMN UPLOAD_PROCEDURE.VISUAL_REPRO_STATUS_CODE IS 'Visual reproductive status code. FK to REPRODUCTIVE_STATUS_LK.CODE';
COMMENT ON COLUMN UPLOAD_PROCEDURE.ULTRASOUND_REPRO_STATUS_CODE IS 'Ultrasound reproductive status code. FK to REPRODUCTIVE_STATUS_LK.CODE';
COMMENT ON COLUMN UPLOAD_PROCEDURE.ULTRASOUND_GONAD_LENGTH IS 'Gonad length measured by ultrasound';
COMMENT ON COLUMN UPLOAD_PROCEDURE.GONAD_CONDITION IS 'Condition of the gonad';
COMMENT ON COLUMN UPLOAD_PROCEDURE.EXPECTED_SPAWN_YEAR IS 'Year of the expected spawn';

COMMENT ON TABLE UPLOAD_PROCEDURE IS 'Table containing the details about procedures performed on the fish.';

REM ### Create DS_PROCEDURE Table ###
SET DEFINE OFF;
CREATE TABLE DS_PROCEDURE (
ID			NUMBER
,P_FID			VARCHAR2(50 BYTE)
,S_FID			VARCHAR2(50 BYTE)
,S_ID			NUMBER
,PURPOSE_CODE		VARCHAR2(2 BYTE)
,PROCEDURE_DATE		DATE
,PROCEDURE_START_TIME	VARCHAR2(11 BYTE)
,PROCEDURE_END_TIME	VARCHAR2(11 BYTE)
,PROCEDURE_BY		VARCHAR2(3 BYTE)
,ANTIBIOTIC_INJECTION_IND	NUMBER
,PHOTO_DORSAL_IND	NUMBER
,PHOTO_VENTRAL_IND	NUMBER
,PHOTO_LEFT_IND		NUMBER
,OLD_RADIO_TAG_NUM	NUMBER
,OLD_FREQUENCY_ID	NUMBER
,DST_SERIAL_NUM		NUMBER
,DST_START_DATE		DATE
,DST_START_TIME		VARCHAR2(11 BYTE)
,DST_REIMPLANT_IND	NUMBER
,NEW_RADIO_TAG_NUM	NUMBER
,NEW_FREQUENCY_ID	NUMBER
,SEX_CODE		VARCHAR2(1 BYTE)
,COMMENTS		VARCHAR2(2000 BYTE)
,FISH_HEALTH_COMMENTS	VARCHAR2(2000 BYTE)
,SPAWN_CODE		VARCHAR2(2 BYTE)
,EVAL_LOCATION_CODE	VARCHAR2(2 BYTE)
,BLOOD_SAMPLE_IND	NUMBER
,EGG_SAMPLE_IND		NUMBER
,VISUAL_REPRO_STATUS_CODE	VARCHAR2(4 BYTE)
,ULTRASOUND_REPRO_STATUS_CODE	VARCHAR2(4 BYTE)
,ULTRASOUND_GONAD_LENGTH	NUMBER
,GONAD_CONDITION		VARCHAR2(50 BYTE)
,EXPECTED_SPAWN_YEAR	NUMBER
,LAST_UPDATED		DATE
,UPLOAD_SESSION_ID	NUMBER
,UPLOADED_BY		VARCHAR2(20 BYTE)
,UPLOAD_FILENAME	VARCHAR2(200 BYTE)
,CONSTRAINT DS_PROCEDURE_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN DS_PROCEDURE.ID IS 'Primary Key. ID';
COMMENT ON COLUMN DS_PROCEDURE.P_FID IS 'Field app procedure ID';
COMMENT ON COLUMN DS_PROCEDURE.UPLOAD_SESSION_ID IS 'Upload Session ID. FK to UPLOAD_SESSION.ID';
COMMENT ON COLUMN DS_PROCEDURE.S_FID IS 'Supplemental ID parent to procedure. FK to UPLOAD_SUPPLEMENTAL.S_FID';
COMMENT ON COLUMN DS_PROCEDURE.S_ID IS 'Supplemental ID parent to procedure. FK to UPLOAD_SUPPLEMENTAL.S_ID';
COMMENT ON COLUMN DS_PROCEDURE.PURPOSE_CODE IS 'Purpose Code. FK to PURPOSE_LK.CODE';
COMMENT ON COLUMN DS_PROCEDURE.PROCEDURE_DATE IS 'Date of the procedure';
COMMENT ON COLUMN DS_PROCEDURE.PHOTO_DORSAL_IND IS 'If have photo of the dorsal side of head. 1  photo taken, 0 no photo';
COMMENT ON COLUMN DS_PROCEDURE.PHOTO_VENTRAL_IND IS 'If have Photo of the ventral side of head. 1  photo taken, 0 no photo';
COMMENT ON COLUMN DS_PROCEDURE.PHOTO_VENTRAL_IND IS 'If have Photo of the left side of head. 1  photo taken, 0 no photo';
COMMENT ON COLUMN DS_PROCEDURE.OLD_RADIO_TAG_NUM IS 'Previous radio tag number';
COMMENT ON COLUMN DS_PROCEDURE.OLD_FREQUENCY_ID IS 'Previous radio tag frequency. FK to FREQUENCY_LK.ID';
COMMENT ON COLUMN DS_PROCEDURE.DST_SERIAL_NUM IS 'DST Serial Number';
COMMENT ON COLUMN DS_PROCEDURE.DST_START_DATE IS 'DST Start Date';
COMMENT ON COLUMN DS_PROCEDURE.DST_START_TIME IS 'DST Start Time';
COMMENT ON COLUMN DS_PROCEDURE.DST_REIMPLANT_IND IS 'Reimplant tag. 1 was reimplanted, 0 not a reimplant';
COMMENT ON COLUMN DS_PROCEDURE.NEW_RADIO_TAG_NUM IS 'New radio tag number';
COMMENT ON COLUMN DS_PROCEDURE.NEW_FREQUENCY_ID IS 'New radio tag frequency. FK to FREQUENCY_LK.ID';
COMMENT ON COLUMN DS_PROCEDURE.SEX_CODE IS 'Sex code for the fish. FK to SEX_LK.CODE';
COMMENT ON COLUMN DS_PROCEDURE.PROCEDURE_BY IS 'Initials of the person performing the procedure';
COMMENT ON COLUMN DS_PROCEDURE.PROCEDURE_START_TIME IS 'Start time of the procedure';
COMMENT ON COLUMN DS_PROCEDURE.PROCEDURE_END_TIME IS 'End time of the procedure';
COMMENT ON COLUMN DS_PROCEDURE.ANTIBIOTIC_INJECTION_IND IS 'If an antibiotic injection was given. 1 - yes, 0 - no';
COMMENT ON COLUMN DS_PROCEDURE.COMMENTS IS 'Comments on the procedure';
COMMENT ON COLUMN DS_PROCEDURE.FISH_HEALTH_COMMENTS IS 'Comments on fish health';
COMMENT ON COLUMN DS_PROCEDURE.SPAWN_CODE IS 'Spawn status code. FK to SPAWN_LK.CODE';
COMMENT ON COLUMN DS_PROCEDURE.EVAL_LOCATION_CODE IS 'Evaluation location code. FK to EVAL_LOCATION_LK.CODE';
COMMENT ON COLUMN DS_PROCEDURE.BLOOD_SAMPLE_IND IS 'If blood sample was taken. 1 - yes, 0 - no';
COMMENT ON COLUMN DS_PROCEDURE.EGG_SAMPLE_IND IS 'If egg sample was taken. 1 - yes, 0 - no';
COMMENT ON COLUMN DS_PROCEDURE.VISUAL_REPRO_STATUS_CODE IS 'Visual reproductive status code. FK to REPRODUCTIVE_STATUS_LK.CODE';
COMMENT ON COLUMN DS_PROCEDURE.ULTRASOUND_REPRO_STATUS_CODE IS 'Ultrasound reproductive status code. FK to REPRODUCTIVE_STATUS_LK.CODE';
COMMENT ON COLUMN DS_PROCEDURE.ULTRASOUND_GONAD_LENGTH IS 'Gonad length measured by ultrasound';
COMMENT ON COLUMN DS_PROCEDURE.GONAD_CONDITION IS 'Condition of the gonad';
COMMENT ON COLUMN DS_PROCEDURE.EXPECTED_SPAWN_YEAR IS 'Year of the expected spawn';

COMMENT ON TABLE DS_PROCEDURE IS 'Table containing the details about procedures performed on the fish.';


### Create REPRODUCTIVE_STATUS_LK Table
CREATE TABLE REPRODUCTIVE_STATUS_LK (
ID		NUMBER
,CODE		VARCHAR2(4 BYTE)
,DESCRIPTION	VARCHAR2(100 BYTE)
,CONSTRAINT REPRODUCTIVE_STATUS_PK PRIMARY KEY (ID)
);
COMMENT ON COLUMN REPRODUCTIVE_STATUS_LK.ID IS 'Primary Key. ID';
COMMENT ON COLUMN REPRODUCTIVE_STATUS_LK.CODE IS 'Reproductive Status Code';
COMMENT ON COLUMN REPRODUCTIVE_STATUS_LK.DESCRIPTION IS 'Description of the reproductive status';

COMMENT ON TABLE REPRODUCTIVE_STATUS_LK IS 'Look up table for reproductive status.';

REM INSERTING into PSPA.REPRODUCTIVE_STATUS_LK
SET DEFINE OFF;
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (1,1,'immature');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (2,1.5,'immature/developing');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (3,2,'developing');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (4,2.5,'developing/vitellogenesis/spermatogenic');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (5,3,'vitellogenesis/spermatogenic');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (6,3.5,'vitellogenesis/spermatigenic/pre-spawning');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (7,4,'pre-spawning');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (8,4.5,'pre-spawning/spawning');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (9,5,'spawning');
Insert into REPRODUCTIVE_STATUS_LK (ID,CODE,DESCRIPTION) values (10,6,'post spawning');
