openapi: "3.0.0"
info:
  version: 0.1.0
  title: US Army Corps of Engineers Pallid Sturgeon
  license:
    name: MIT
servers:
  - url: http://localhost:8080/psapi
paths:
  /seasons:
    get:
      summary: List Seasons
      operationId: GetSeasons
      tags:
        - seasons
      responses:
        '200':
          description: Array of seasons
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/season"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /siteUpload:
    post:
      tags:
      - "siteUpload"
      summary: "Add a site upload"
      description: ""
      operationId: "addSiteUpload"
      requestBody:
        description: "Site upload object that needs to be uploaded"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/uploadSite"
      responses:
        "405":
          description: "Invalid input"
        default:
          description: "successful operation"
components:
  schemas:
    season:
      type: object
      required:
        - id
        - code
        - description
        - fieldAppFlag
        - ProjectCode
      properties:
        id:
          type: integer
          format: int32
        code:
          type: string
        description:
          type: string
        fieldAppFlag:
          type: string
        ProjectCode:
          type: integer
          format: int32
    uploadSite:
      type: object
      required:
        - siteId
        - uploadSessionId
        - uploadFilename
      properties:
        siteId:
          type: integer
          format: int32
        siteFid:
          type: string
        siteYear:
          type: integer
          format: int32
        fieldofficeID:
          type: string
        fieldOffice:
          type: string
        projectId:
          type: integer
          format: int32
        project:
          type: string
        segmentId:
          type: integer
          format: int32
        segment:
          type: string
        seasonId:
          type: string
        season:
          type: string
        bend:
          type: integer
          format: int32
        bendrn:
          type: string
        bendRiverMile:
          type: number
        comments:
          type: string
        uploadSessionId:
          type: integer
          format: int32
        uploadFilename:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string