name: Build API Develop

on:
  push:
    branches: [dev]
  workflow_dispatch:
jobs:
  build:
    name: build
    uses: USACE/pallid-sturgeon-api/.github/workflows/build.yaml@dev
    with:
      tag-name: dev
      aws-region: us-gov-west-1
      aws-account: 718787032875
      ecr-repository: pallid-sturgeon-api-dev
    secrets: inherit